---
title: "gaa_components_pca_kmeans"
author: "Conor Tompkins"
date: "August 20, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(broom)
library(ggfortify)
library(viridis)
library(janitor)
library(ggrepel)

theme_set(theme_minimal())
```

```{r}
read_csv("data/EW_GAA.csv") %>% 
  clean_names() %>% 
  arrange(desc(gaa)) %>% 
  mutate(position = fct_inorder(as.character(position)),
         id = str_c(player, team, season, sep = ", "),
         id = as.factor(id),
         season = as.factor(as.character(season))) %>% 
  select(id, player, season, team, position, gaa) -> df_lookup

read_csv("data/EW_GAA.csv") %>% 
  clean_names() %>% 
  filter(toi_all >= 500) %>% 
  mutate(position = fct_inorder(as.character(position)),
         id = str_c(player, team, season, sep = ", "),
         season = as.factor(as.character(season))) %>% 
  select(id, position, evo_aa_60:draw_aa_60) -> df

df <- replace(df, is.na(df), 0)

df %>% 
  select(-position) -> df
  
df %>% 
  count(id, sort = TRUE)
```

```{r}
df %>% 
  ggplot(aes(evo_aa_60, draw_aa_60)) +
  geom_point() +
  geom_smooth()


df %>%
  select(id, evo_aa_60:draw_aa_60) %>% 
  gather(variable, value, -c(id, evo_aa_60)) %>% 
  ggplot(aes(evo_aa_60, value)) +
  geom_point(alpha = .1) +
  geom_smooth() +
  facet_wrap(~variable, scales = "free")
```

```{r}
df %>%
  remove_rownames() %>% 
  column_to_rownames(var = "id") -> df_pca
```

```{r}
df_pca %>% 
  prcomp(scale = TRUE) -> pc
```

```{r}
pc %>% 
  tidy() %>% 
  head()
```

```{r}
pc %>% 
  tidy("pcs")
```

```{r}
pc %>% 
  augment(data = df_pca) %>% 
  as_tibble() -> au

au %>% 
  head()
```

```{r}
pc %>% 
  tidy("pcs") %>%
  select(-std.dev) %>% 
  gather(measure, value, -PC) %>% 
    ggplot(aes(PC, value)) +
    geom_line() +
    geom_point() +
    facet_wrap(~measure) +
    labs(title = "Variance explained by each principal component",
         x = "Principal Component",
         y = NULL) +
    scale_x_continuous(breaks = 1:7)
```

```{r}
df %>% 
  nest() %>% 
  mutate(pca = map(data, ~ prcomp(.x %>% select(-id), 
                                  center = TRUE, scale = TRUE)),
         pca_aug = map2(pca, data, ~augment(.x, data = .y))) -> df_pca2
```

```{r fig.height=12, fig.width=12}
df_pca2 %>% 
mutate(
    pca_graph = map2(
      .x = pca,
      .y = data,
      ~ autoplot(.x, loadings = TRUE, loadings.label = TRUE,
                 loadings.label.repel = TRUE, loadings.label.size = 8,
                 alpha = .5,
                 data = .y) +
        theme_bw() +
        labs(x = "Principal Component 1",
             y = "Principal Component 2",
             title = "First two principal components of PCA on EvolvingWild GAA data")
    )
  ) %>%
  pull(pca_graph)
```

```{r}
au %>% 
  rename(id = .rownames) %>% 
  gather(variable, value, -c(id)) -> au_long
```

```{r}
au_long %>% 
  filter(str_detect(variable, ".fitted")) %>% 
  spread(variable, value) %>% 
  select(-id) -> df_kmeans
```

```{r}
kclusts <- tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~kmeans(df_kmeans, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, df_kmeans)
  )

kclusts
```

```{r}
clusters <- kclusts %>%
  unnest(tidied)

assignments <- kclusts %>% 
  unnest(augmented)

clusterings <- kclusts %>%
  unnest(glanced, .drop = TRUE)
```

```{r}
p1 <- ggplot(assignments, aes(.fittedPC1, .fittedPC2)) +
  geom_point(aes(color = .cluster), alpha = .2) + 
  facet_wrap(~ k)
p1
```

```{r}
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = 1:9)
```

```{r}
au_long %>% 
  filter(str_detect(variable, ".fitted")) %>% 
  spread(variable, value) %>% 
  select(-id) -> df_kmeans

kclust <- kmeans(df_kmeans, centers = 2)

kclust %>% 
  augment(au_long %>% 
    filter(str_detect(variable, ".fitted")) %>% 
    spread(variable, value)) %>% 
    left_join(df_lookup) -> df_kmeans
```

```{r fig.height=12, fig.width=15}
df_kmeans %>% 
    mutate(outlier = case_when(abs(.fittedPC1) >= 4 | abs(.fittedPC2 >= 3.5) ~ TRUE)) %>% 
  filter(outlier == TRUE) -> df_kmeans_outlier

df_kmeans %>% 
  ggplot(aes(.fittedPC1, .fittedPC2, color = position)) +
  geom_point(alpha = .7) +
  geom_label_repel(data = df_kmeans_outlier %>% filter(outlier == TRUE), aes(label = id), size = 4) +
  labs(title = "EvolvingWild GAA",
       subtitle = "EV/PP/SH GAA")
```

```{r}
df_kmeans %>% 
  arrange(.fittedPC1) %>% 
  mutate(id = factor(id)) %>% 
  group_by(position) %>% 
  top_n(20, .fittedPC1) %>% 
  ggplot(aes(reorder(id, .fittedPC1), .fittedPC1, alpha = gaa)) +
  geom_col(color = "black") +
  coord_flip() +
  #scale_y_reverse() +
  facet_wrap(~position, 
             scale = "free",
             ncol = 2) +
  labs(title = "EvolvingWild GAR",
       subtitle = "Top 20 per position in absolute principle component value")
```

```{r}
df_kmeans %>% 
  arrange(.fittedPC1) %>% 
  mutate(id = factor(id)) %>% 
  group_by(position) %>% 
  top_n(20, desc(.fittedPC1)) %>% 
  ggplot(aes(reorder(id, desc(.fittedPC1)), .fittedPC1, alpha = gaa)) +
  geom_col(color = "black") +
  coord_flip() +
  scale_y_reverse() +
  facet_wrap(~position, 
             scale = "free",
             ncol = 2) +
  labs(title = "EvolvingWild GAA",
       subtitle = "Top 20 per position in absolute principle component value")
```


```{r}
df_kmeans %>% 
  arrange(desc(.fittedPC2)) %>% 
  mutate(id = factor(id)) %>% 
  group_by(position) %>% 
  top_n(20, desc(.fittedPC2)) %>% 
  ggplot(aes(reorder(id, desc(.fittedPC2)), .fittedPC2, alpha = gaa)) +
  geom_col(color = "black") +
  coord_flip() +
  scale_y_reverse() +
  facet_wrap(~position, 
             scale = "free",
             ncol = 2) +
    labs(title = "EvolvingWild GAA",
       subtitle = "Top 20 per position in absolute principle component value")
```

```{r}
df_kmeans %>% 
  arrange(.fittedPC2) %>% 
  mutate(id = factor(id)) %>% 
  group_by(position) %>% 
  top_n(20, .fittedPC2) %>% 
  ggplot(aes(reorder(id, .fittedPC2), .fittedPC2, alpha = gaa)) +
  geom_col(color = "black") +
  coord_flip() +
  #scale_y_reverse() +
  facet_wrap(~position, 
             scale = "free",
             ncol = 2) +
    labs(title = "EvolvingWild GAA",
       subtitle = "Top 20 per position in absolute principle component value")
```

```{r}
df_kmeans %>% 
  gather(pc, pc_value, -c(id, player, season, team, .cluster, position, gaa, .fittedPC1)) %>% 
  ggplot(aes(.fittedPC1, pc_value, color = .cluster)) +
  geom_point(alpha = .4) +
  facet_wrap(~pc)
```

```{r}
df_kmeans %>%
  #filter(season == 20172018) %>% 
  ggplot(aes(.fittedPC1, .fittedPC2, label = player)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  #geom_point(alpha = .2) +
  stat_density_2d(aes(fill = stat(level)), geom = "polygon") +
  #geom_label_repel()
  facet_wrap(~season)
```

```{r}
df_kmeans %>%
  filter(player %in% c("EVGENI.MALKIN", "SIDNEY.CROSBY", "ALEX.OVECHKIN")) %>% 
  ggplot(aes(.fittedPC1, .fittedPC2, label = season)) +
  geom_point() +
  geom_path() +
  geom_label_repel(aes(alpha = season)) +
  facet_wrap(~player) +
  scale_alpha_discrete(range = c(.3, 1))
```

```{r eval = FALSE}
library(gganimate)
library(gapminder)

ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')

df_kmeans %>% 
  filter(player == "SIDNEY.CROSBY") %>% 
  ggplot(aes(.fittedPC1, .fittedPC2, label = season)) +
  geom_point() +
  geom_path() +
  geom_label_repel(aes(alpha = season)) +
  facet_wrap(~player) +
  scale_alpha_discrete(range = c(.3, 1))



```



